# Generated by Django 4.2.1 on 2023-05-11 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('little_description', models.CharField(blank=True, max_length=500, null=True)),
                ('main_description', models.CharField(blank=True, max_length=50000, null=True)),
                ('likes', models.IntegerField(default=0)),
                ('date_of_public', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(default='Ivanov I.I.', max_length=200)),
                ('bornAge', models.CharField(default=18, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('projects', models.ManyToManyField(related_name='skills', to='app.project')),
                ('users', models.ManyToManyField(related_name='skills', to='app.usermodel')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='applications',
            field=models.ManyToManyField(related_name='wishing', to='app.usermodel'),
        ),
        migrations.AddField(
            model_name='project',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.usermodel'),
        ),
    ]
