# Generated by Django 4.2.1 on 2023-05-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='users',
        ),
        migrations.AddField(
            model_name='project',
            name='projects',
            field=models.ManyToManyField(related_name='projects', to='app.skill'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='skills',
            field=models.ManyToManyField(related_name='users', to='app.skill'),
        ),
    ]
