# Generated by Django 4.2.1 on 2023-05-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_skill_projects_remove_skill_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projects',
            new_name='skills',
        ),
    ]
