# Generated by Django 4.2.1 on 2023-05-12 10:14

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_projects_project_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='color',
            field=colorfield.fields.ColorField(default='FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
