# Generated by Django 4.2.1 on 2023-05-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_project_options_remove_usermodel_bornage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='born',
        ),
    ]
