# Generated by Django 4.2.1 on 2023-05-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_usermodel_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='about',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
