# Generated by Django 4.2.1 on 2023-05-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='usermodel',
            name='contacts',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
